### ISSUE TITLE
issue while running spm design

### ISSUE THREAD

**Issue by praharshapm** [nickson-jose/openlane_build_script#1]
Hi Nickson,
i ran this script. I think the first and second step for installation have to be swapped because after logging into root using sudo -i, the cloned repo is not visible. so would have to git clone again.

Another issue, I installed openlane successfully and ran the test design using :
bash-4.1$ ./flow.tcl -design spm

And I am getting the following error:
couldn't read file "/root/openlane_build_script/work/tools/openlane_working_dir/pdks/sky130A/libs.tech/openlane/config.tcl": permission denied

I have called the docker from root itself.,but still its showing permission denied.
could you help me resolve this issue?

**Comment by nickson-jose** [comment]
Hi Praharsha,

Please find the resolution to below 2 issues assuming that you are correctly run the docker command from ~/openlane directory:

1) couldn't read file "/root/openlane_build_script/work/tools/openlane_working_dir/pdks/sky130A/libs.tech/openlane/config.tcl": Execute
`export PDK_ROOT=<absolute path to where skywater-pdk and open_pdks reside>` 
*For eg:* export PDK_ROOT= /home/<username>/Desktop/work/tools/openlane_working_dir/pdks

post executing the above command invoke docker as:
`docker run -it -v $(pwd):/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -e PDK_ROOT=$PDK_ROOT -u $(id -u $USER):$(id -g $USER) openlane:rc2`

Add the export variable (PDK_ROOT) to your environment or you will have to execute the same every time you restart your terminal. 

2) For permission denied while invoking docker:

Add your user to docker group with below command
`sudo usermod -aG docker ${USER}`

Hope that resolves the issues.

-Nickson

**Comment by MohamedAliYounis** [comment]
I have a similar issue with reading config.tcl file but for a different reason, it says that no such file or directory, and the file exists and has all permissions.
if anyone can help. thanks in advance.
Regards,
Younis
![image](https://user-images.githubusercontent.com/47182179/166613893-73538bf6-d9cd-4014-89b3-5d615a302e41.png)
