### ISSUE TITLE
Repository name must be lowercase

### ISSUE THREAD

**Issue by GleidsonLeite** [nickson-jose/openlane_build_script#2]
Hello,

Thanks to this repository, it's help me a lot. I'm having a problem with docker, when i tried to execute the following command:

`docker run -it -v $(pwd):/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -e PDK_ROOT=$PDK_ROOT -u $(id -u $USER):$(id -g $USER) openlane:rc6`

It returns the error message:

docker: invalid reference format: repository name must be lowercase. 

could you help me to solve it?

**Comment by nickson-jose** [comment]
You might want to check the below link. Seems a syntax issue.
https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase

Closing the issue now. Feel free to reopen incase it doesn't work.
