### ISSUE TITLE
Updation of openlane_script_rc6.sh and openlane_script_wo_depends.sh

### ISSUE THREAD

**Issue by Badboy1307** [nickson-jose/openlane_build_script#3]
Please update both openlane_script_rc6.sh and openlane_script_wo_depends.sh with **git clone https://github.com/efabless/openlane.git** as your branch version is showing some errors as it's outdated after OpenLane got cloned there were errors and sometimes the process gets stuck in the middle. 

Please update  https://github.com/efabless/openlane with https://github.com/The-OpenROAD-Project/OpenLane/tree/v0.15 which is the stable version for OpenLane.

**Comment by nickson-jose** [comment]
Thanks for pointing that out @Badboy1307 . It has been corrected.
